version: "3.8"

services:
  mariflow-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mariflow-api
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Configurações do Servidor
      - PORT=3000
      - NODE_ENV=${NODE_ENV:-production}

      # Configurações do WhatsApp
      - WHATSAPP_SESSION_PATH=/app/sessions
      - WHATSAPP_QR_TIMEOUT=${WHATSAPP_QR_TIMEOUT:-60000}
      - WHATSAPP_AUTH_STRATEGY=${WHATSAPP_AUTH_STRATEGY:-local}

      # Configurações de Segurança
      - API_KEY=${API_KEY:-your-secret-api-key-here}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}

      # Configurações de Log
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=/app/logs/app.log

      # Configurações do Swagger
      - SWAGGER_TITLE=${SWAGGER_TITLE:-MariFlow API}
      - SWAGGER_DESCRIPTION=${SWAGGER_DESCRIPTION:-MariFlow - API REST para integração com WhatsApp}
      - SWAGGER_VERSION=${SWAGGER_VERSION:-1.0.0}
      - SWAGGER_HOST=${SWAGGER_HOST:-localhost:${PORT:-3000}}

      # Configurações de Upload
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-10485760}
      - UPLOAD_PATH=/app/uploads

      # Configurações de Cache
      - CACHE_TTL=${CACHE_TTL:-300000}

      # Configurações do Puppeteer
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
    volumes:
      # Persistir sessões do WhatsApp
      - whatsapp_sessions:/app/sessions
      # Persistir logs
      - app_logs:/app/logs
      # Persistir uploads
      - app_uploads:/app/uploads
    networks:
      - mariflow-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_sessions:
    driver: local
  app_logs:
    driver: local
  app_uploads:
    driver: local

networks:
  mariflow-network:
    driver: bridge
